/* date = August 20th 2025 10:24 pm */

#ifndef SKATE_KEYCODES_H

#define SKEY(v) SAPP_KEYCODE_##v
#define SMBT(v) SAPP_MOUSEBUTTON_##v

#define S_RELEASED INPUT_EVENT_TYPE_RELEASED
#define S_PRESSED  INPUT_EVENT_TYPE_PRESSED
#define S_HELD     INPUT_EVENT_TYPE_HELD

#define PRESSED_AND_HELD   S_PRESSED  | S_HELD
#define HELD_AND_RELEASED  S_RELEASED | S_HELD





#define SKATE_KEYCODE_FWD SKEY(W)
#define SKATE_KEYCODE_LFT SKEY(A)
#define SKATE_KEYCODE_BCK SKEY(S)
#define SKATE_KEYCODE_RGT SKEY(D)

#define SKATE_BUTTON_LEFT   SMBT(LEFT)
#define SKATE_BUTTON_RIGHT  SMBT(RIGHT)
#define SKATE_BUTTON_MIDDLE SMBT(MIDDLE)

#define SKATE_KEYCODE_LOOK_ORIGIN SKEY(5)

#define SKATE_KEYCODES_H
#endif //SKATE_KEYCODES_H
